### PR TITLE
Appended API example

### PR DESCRIPTION
**Pull request by hippolyt**
Supports #685 
https://github.com/resin-io/resin-supervisor/issues/685

Made the documentation of already existing API v2 functions a little bit more complete.
Added api proxy example to /supervisor/v2/applications/state

### CODE REVIEW

**Comment by CameronDiver** [comment]
Hey @hippolyt thanks for doing this! Sorry for the delay I've been having some time off. Are you happy to rebase and remove the merge commit and we can get this approved and merged :) ? I'm also happy to take over your branch for you if you prefer.

**Comment by hippolyt** [comment]
Hi @CameronDiver, 

thanks.
It would be cool if you could take this over.

I would like to contribute to the API in the future, but I am not sure yet about how the process works.

Greetings!

**Comment by CameronDiver** [comment]
Not a problem @hippolyt and thanks again for the PR!

I'm more than happy to set aside some time for you if you'd like to go through things. Probably the best way to do this would be to email me on cameron@balena.io so just shoot an email across if this is something you'd like to do.

**Comment by CameronDiver** [comment]
I updated and rebaed the PR, and also pinned the dockerode types to avoid a build issue, pending the merge of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30343.

**Comment by CameronDiver** [comment]
@resinci retest

**Comment by CameronDiver** [comment]
All merged and closed. Thanks for the PR @hippolyt!

**Pull request merged**
