### PR TITLE
Handle delete of multiple images with same dockerImageId

### PR DESCRIPTION
**Pull request by pipex**
A docker-compose.yml with the following structure

```
version: '2.1'
services:
  app_1:
    build: ./noisy-1
    image: noisy1
  app_2:
    build: ./noisy-1
    image: noisy1
  app_3:
    build: ./noisy-1
    image: noisy1
```

Will lead to the supervisor creating multiple image database entries
with the same dockerId (this is because of how the engine handles this
particular case). This case is not handled by the removal process
leading to image pile up and increased disk usage.

Change-type: patch
Signed-off-by: Felipe Lalanne <felipe@balena.io>
Connects-to: #1434

### CODE REVIEW

**Comment by 20k-ultra** [comment]
let's make this PR ready for review. We have confirmed this PR fixes the issue.

**Comment by pipex** [comment]
When do you have some time? We can pair program some tests, which is what I suppose it's missing

**Comment by 20k-ultra** [comment]
This PR is being blocked due to lack of testing. I have been working on adding these but since this PR touches code that uses the knex database and dockerode there is a lot of mocking required to correctly test. I really want this merged so I want to approve and created https://github.com/balena-io/balena-supervisor/issues/1492 to come back right after to add testing. I believe this is acceptable because there isn't any test coverage for the current functionality which means the argument for avoiding merging due to lack of testing is already lost.

**Comment by pipex** [comment]
That's similar to what I experienced trying to test the database migrations, that's why I created this https://github.com/balena-io/balena-supervisor/issues/1475

If you want we can work together to try to tackle the database testing stuff @20k-ultra

**Review by 20k-ultra — DISMISSED** [review]
This PR has been tested on real devices for few weeks so he lack of testing is fine for now but should be added soon. For future reference the timeout to avoid race condition is due to that these container operations such as remove, download, start etc are all done in parallel. If this timeout was not present the code will still work but an exception is logged and then it runs again but with the timeout it's enough time that it never throws the exception. Not ideal but works right now.

**Comment by 20k-ultra** [comment]
@balena-ci retest

**Comment by 20k-ultra** [comment]
@balena-ci retest please

**Comment by 20k-ultra** [comment]
@balena-ci test

**Review by 20k-ultra — APPROVED** [review]

**Pull request merged**
