### PR TITLE
Add dependabot configuration

### PR DESCRIPTION
**Pull request by 20k-ultra**
Closes: #1508
Change-type: patch
Signed-off-by: Miguel Casqueira <miguel@balena.io>

### CODE REVIEW

**Comment by 20k-ultra** [comment]
@balena-ci I self-certify!

**Comment by pipex** [comment]
Wasn’t there some dependabot configuration somewhere @20k-ultra ?

**Comment by 20k-ultra** [comment]
Do you mean an existing config in the Supervisor repo @pipex ? If so, no.

**Comment by pipex** [comment]
Yeah, but I’ve seen dependabot PRs before (see [here](https://github.com/balena-io/balena-supervisor/pull/1546). Where did they come from?

**Comment by 20k-ultra** [comment]
Yeah, github acquired dependabot and it is opt-out meaning you have to disable it on all your repositories so Github stops sending the random PRs. https://github.com/dependabot/feedback/issues/216#issuecomment-627947276

**Comment by pipex** [comment]
Oh, I see.

**Pull request merged**
