### PR TITLE
Avoid cloneDeep when copying target state

### PR DESCRIPTION
**Pull request by CameronDiver**
Closes: https://github.com/balena-io/balena-supervisor/issues/1042
Change-type: patch
Signed-off-by: Cameron Diver <cameron@balena.io>

### CODE REVIEW

**Comment by xginn8** [comment]
https://github.com/balena-io/balena-supervisor/issues/1042 for reference

**Comment by hedss** [comment]
This is all fine locally building from source. Waiting for the builds to work correctly to test image, but should be fine.

**Comment by hedss** [comment]
Right, I've tested this to death. It works.

**Comment by hedss** [comment]
@balena-ci retest

**Pull request merged**
